openapi: 3.0.3
info:
  title: Identifier List API
  version: 1.0.0
security:
  - ApiKeyAuth: []
paths:
  /identifier-list/new-reference:
    post:
      summary: Create a new identifier
      operationId: newReferences
      responses:
        default:
          description: error occured.
          content:
            "application/problem+json":
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "200":
          description: Successfully created new identifier
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Reference'
      parameters:
        - name: X-Api-Key
          in: header
          schema:
            type: string
  /{list-id}:
    get:
      summary: Get identifier status list
      parameters:
        - in: path
          name: list-id
          required: true
          description: The id of the identifier list
          schema:
            type: integer
      responses:
        default:
          description: error occured.
          content:
            "application/problem+json":
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        '200':
          description: Identifier status
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IdentifierList'

  /identifier-list/update:
    patch:
      summary: Update the status of an identifier
      operationId: updateStatus
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateStatusRequest'

      responses:
        default:
          description: error occured.
          content:
            "application/problem+json":
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '204':
          description: Status updated successfully
      parameters:
        - name: X-Api-Key
          in: header
          schema:
            type: string

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-Api-Key
  schemas:
    ErrorResponse:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
        message:
          type: string
    Reference:
      type: object
      required:
        - uri
        - identifierUuid
      properties:
        uri:
          type: string
          format: int32
          minimum: 0
        identifierUuid:
          type: string
          format: UUID
    UpdateStatusRequest:
      type: object
      required:
        - identifierUuid
        - uri
        - value
      properties:
        identifierUuid:
          type: string
          format: UUID
        uri:
          type: string
        value:
          type: integer
          format: int32
          minimum: 0
          maximum: 1
    IdentifierList:
      type: object
      properties:
        identifier_list:
          type: object
          additionalProperties:
            type: object
            properties:
              status:
                type: integer
                format: int32
                description: Status of the identifier