CREATE TABLE identifier_lists (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);

CREATE TABLE identifiers (
    id UUID PRIMARY KEY,
    list_id BIGINT NOT NULL,
    status SMALLINT NOT NULL DEFAULT 0,
    status_change_count INT NOT NULL DEFAULT 0,
    FOREIGN KEY (list_id) REFERENCES identifier_lists (id) ON DELETE CASCADE
);

CREATE INDEX idx_identifiers_list_id ON identifiers (list_id);